### Items
GET http://localhost:3001/api/items
###
POST http://localhost:3001/api/items
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJAdXNlci5maSIsImlkIjoiNjFhOTJmNDQzOWYwMjc0YmJiMTIxMzUzIiwiaWF0IjoxNjM5MjI0NDk3fQ.dsh53sD4ETzQJbrPeQGVcSxBnKpuDqREXoEpb6jxh04

{
    "type":"Omena",
    "count":"13",
    "price":"13"
}


### Create
POST http://localhost:3001/api/items
Content-Type: application/json

{
    "type":"Omena",
    "count":"12",
    "price":"12"
}

### Create
POST http://localhost:3001/api/login/
Content-Type: application/json

{
    "username":"user@user.fi",
    "password":"password"
}
### Create
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username":"qwe",
    "password":"4123",
    "firstName": "Dahir",
    "lastName": "Hussein"
}
### Read
GET http://localhost:3001/api/login
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJAdXNlci5maSIsImlkIjoiNjFhOTJmNDQzOWYwMjc0YmJiMTIxMzUzIiwiaWF0IjoxNjM5MjI0NDk3fQ.dsh53sD4ETzQJbrPeQGVcSxBnKpuDqREXoEpb6jxh04

### Read
GET http://localhost:3001/api/login
### Read
GET http://localhost:3001/api/items
### Read
GET http://localhost:3001/api/users
### Read
GET http://localhost:3001/api/users/61bc60ae98b7ab17a9220b5e
### Read
GET http://localhost:3001/api/users/61bc60ae98b7ab17a9220b5e/items

### Post
POST http://localhost:3001/api/users/61bc60ae98b7ab17a9220b5e/items
Content-Type: application/json

{
    "type":"Omena",
    "count":1392,
    "price":5
}
### Read
GET http://localhost:3001/api/items/61812c685e79ac2da21a7dda
### Update
PUT http://localhost:3001/api/items/61812c685e79ac2da21a7dda
Content-Type: application/json

{
    "type":"Banaani",
    "count":123,
    "price":12
}
### Delete
DELETE http://localhost:3001/api/items/61812c685e79ac2da21a7ddd
### Delete
DELETE http://localhost:3001/api/signup
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vdXNlMTIzIiwiaWQiOiI2MWFjZmY4MjRkODZiMmE4ZjY0ZDcxYzIiLCJpYXQiOjE2Mzg3Mjc1NjJ9.aIKJnSjKi8voMgQvr0PaH3WQwY7Fw0OsnvGjGdrOhnA
### Delete
DELETE http://localhost:3001/api/users